-- Placeholder migration (intentionally empty).
-- The is_demo + demo_expires_at columns are now set directly inside
-- create_demo_company() in a single transaction, instead of a separate
-- UPDATE from the edge function.
